export { default as FormGeneral } from './form-general'
export { default as Card } from './card'
export { default as Resume } from './resume'
export { default as Thumbnail } from './thumbnail'
export { default as List } from './list'
export { default as Input } from './input-institution'
